[package]
name = "use-pitch"
description = "Symbolic pitch metadata primitives for RustUse."
publish = true
authors.workspace = true
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "README.md"
documentation = "https://docs.rs/use-pitch"
keywords = ["music", "pitch", "metadata"]
categories = ["data-structures", "no-std::no-alloc"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
